#KootPanKing Default Settings
alwaysOnTop=true
startHidden=false
showDigital=false
showNumbers=false
theme=Black
opacity=1.0
cityName=Local
timeZone=Asia/Seoul
showInterval=0
animInterval=0
fontName=Georgia
fontSize=14
digFontName=\uAD74\uB9BC
digFontSize=14
bgColor=
bgImagePath=
tickColor=
tickVisible=true
secondVisible=true
hourColor=-14798126
minuteColor=-16080866
secondColor=-2351586
numberColor=
digitalColor=-1
showLunar=false
slideFolder=
slideInterval=2
slideOverlay=0
slideEnabled=false
borderColor=
borderWidth=-1
borderAlpha=255
borderVisible=false
chimeEnabled=false
chimeFile=
chimeFull=false
chimeMinutes=0
camera.url=http://192.168.0.100:8080/video
cameraMode=false
galaxyMode=false
matrixMode=false
tg.botToken=
tg.myChatId=
tg.polling=false
gmail.from=
gmail.pass=
gmail.lastTo=
kakao.apiKey=
kakao.clientSecret=
